# Generated by Django 5.1.2 on 2024-10-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id_doc', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_doc', models.CharField(max_length=100)),
                ('email_doc', models.EmailField(max_length=100)),
                ('senha_doc', models.CharField(max_length=6)),
                ('cargo_doc', models.CharField(max_length=100)),
                ('tel_doc', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
