# Generated by Django 5.1.3 on 2024-11-12 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomap', '0005_alter_docente_id_doc_alter_equipamento_id_equip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservaadm',
            fields=[
                ('id_reserva', models.IntegerField(primary_key=True, serialize=False)),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField()),
                ('status_reserva', models.CharField(max_length=15)),
                ('nome_adm', models.CharField(max_length=100)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomap.sala')),
            ],
        ),
    ]
