# Generated by Django 5.1.3 on 2024-11-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomap', '0006_reservaadm'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaView',
            fields=[
                ('id_sala', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_sala', models.CharField(max_length=100)),
                ('capac_sala', models.IntegerField()),
                ('loc_sala', models.CharField(max_length=15)),
                ('status_sala', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'view_salas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewReservasAdmin',
            fields=[
                ('id_reserva', models.IntegerField(primary_key=True, serialize=False)),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField()),
                ('nome_sala', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'view_reservas_admin',
                'managed': False,
            },
        ),
    ]
