# Generated by Django 5.1.3 on 2024-11-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomap', '0008_reservaultimasemanaadmin_viewdadosdocentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaUltimaSemanaDocente',
            fields=[
                ('id_reserva', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_doc', models.CharField(max_length=100)),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField()),
                ('status_reserva', models.CharField(max_length=15)),
                ('id_sala', models.IntegerField()),
            ],
            options={
                'db_table': 'reservas_ultima_semana_docente',
                'managed': False,
            },
        ),
    ]
