# Generated by Django 5.1.2 on 2024-11-26 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomap', '0011_turno_reservaadm_turno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turno',
            options={'managed': False},
        ),
    ]
