# Generated by Django 5.1.2 on 2024-11-26 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomap', '0012_alter_turno_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reserva',
            table='reservas',
        ),
    ]
