# Generated by Django 5.1.2 on 2024-11-26 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomap', '0013_alter_reserva_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'managed': False},
        ),
    ]
