# Generated by Django 5.1.2 on 2024-11-26 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomap', '0014_alter_reserva_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={},
        ),
    ]
