# Generated by Django 5.1.2 on 2024-11-28 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomap', '0015_alter_reserva_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaadm',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomap.sala'),
        ),
    ]
