# Generated by Django 5.1.2 on 2024-11-28 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomap', '0018_alter_reservaadm_sala_alter_reservaadm_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaadm',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomap.sala'),
        ),
        migrations.AlterField(
            model_name='reservaadm',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roomap.turno'),
        ),
    ]
