# Generated by Django 5.1.2 on 2024-11-28 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomap', '0019_alter_reservaadm_sala_alter_reservaadm_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaadm',
            name='sala',
            field=models.ForeignKey(db_column='id_sala', on_delete=django.db.models.deletion.CASCADE, to='roomap.sala'),
        ),
    ]
