# Generated by Django 5.1.2 on 2024-11-28 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomap', '0020_alter_reservaadm_sala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaadm',
            name='turno',
            field=models.ForeignKey(blank=True, db_column='turno_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='roomap.turno'),
        ),
    ]
