# Generated by Django 5.1.2 on 2024-11-28 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomap', '0021_alter_reservaadm_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='turno',
            field=models.ForeignKey(blank=True, db_column='turno_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='roomap.turno'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='email_doc',
            field=models.ForeignKey(db_column='email_doc', on_delete=django.db.models.deletion.CASCADE, to='roomap.docente'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='sala',
            field=models.ForeignKey(db_column='id_sala', on_delete=django.db.models.deletion.CASCADE, to='roomap.sala'),
        ),
    ]
