# Generated by Django 5.1.2 on 2024-12-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomap', '0022_reserva_turno_alter_reserva_email_doc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaMesAdmin',
            fields=[
                ('id_reserva', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_adm', models.CharField(max_length=100)),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField()),
                ('status_reserva', models.CharField(max_length=15)),
                ('id_sala', models.IntegerField()),
                ('turno_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reservas_ultimo_mes_admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReservaMesDocente',
            fields=[
                ('id_reserva', models.IntegerField(primary_key=True, serialize=False)),
                ('email_doc', models.EmailField(max_length=254)),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField()),
                ('status_reserva', models.CharField(max_length=15)),
                ('id_sala', models.IntegerField()),
                ('turno_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reservas_ultimo_mes_docente',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ReservaUltimaSemanaAdmin',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='email_doc',
            field=models.EmailField(max_length=254),
        ),
    ]
